version: '3.5'

services:
  server:
    restart: always
    privileged: true
    container_name: battleships-blazor
    ports:      
      - "5020:5000"
    networks:
      - blazor
    build:
      context: .
      dockerfile: Dockerfile

networks:
  blazor: